<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf94ef5f382a5440f1903252dcb29bff5
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Rakit\\Validation\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rakit\\Validation\\' => 
        array (
            0 => __DIR__ . '/..' . '/rakit/validation/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf94ef5f382a5440f1903252dcb29bff5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf94ef5f382a5440f1903252dcb29bff5::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf94ef5f382a5440f1903252dcb29bff5::$classMap;

        }, null, ClassLoader::class);
    }
}
